# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f09079e198800216a59b5a3ca4726d6e7c541378d97b8ccaf65ce361cc823495ec3cf9716361d16337c3eec81e3ee92c67224ab7ea45d31bb7723a06427a95ec
  twitter_consumer_key: 'BKVxuRlX7tN8IkF2FPicNJpP2'
  twitter_consumer_secret: 'QxWhzLUAMtznt96ZPaOWsENFj5YwXnnT63QTXwp9DZ6RW9ATDX'
  twitter_oauth_token: '21260646-23Ovaksn5ChqfteANQzjQ3uuxdAu8hJCf7NBd8Bfg'
  twitter_oauth_token_secret: 'P4uAkjOyJkkNBOfxigwop0tCsD48174lIajzXeAYiaLbo'
  instagram_client_id: cd991b00b96e48df8cd295b0d36b9d8d
  
test:
  secret_key_base: acf9f9bd68188bba69db495dbd6be26430f6aba0d26244a9e6523688c64e4f8312743c9d7ffcff0fb03faf68b9cd20bc582aff73c4c59574e889b7bb8fde856d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
